<a href="https://colab.research.google.com/github/DamodaraBarbosa/infos_xbox_game_pass/blob/main/Merge_Infos_Game_Pass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando as bibliotecas a serem utilizadas

In [1]:
import pandas as pd
import string

# Importando as bases de dados

In [2]:
# tabela com os jogos que estão ou estiveram no serviço Game Pass:

df_gamepass = pd.read_csv('/content/drive/MyDrive/Dados Xbox/Game Pass Master List - Master List (1).csv')
df_gamepass.columns = df_gamepass.iloc[0]
df_gamepass.drop([0], inplace= True)
df_gamepass.head()

,Game,System,xCloud,Status,Added,Removed,Months,Release,Age,Metacritic,Completion,Genre (Giantbomb),Xbox Series X|S,Owner Notes,ESRB,ESRB Content Descriptors,Public Notes,Retail
1,Persona 3: Portable,Xbox / PC,Yes,Coming Soon,Jan 2023,NaN,-2.63,Nov 2009,13.22,89,65.5,Role-Playing,NaN,NaN,M,"Blood, Language, Partial Nudity, Sexual Themes...",NaN,NaN
2,Persona 4: Golden,Xbox / PC,Yes,Coming Soon,Jan 2023,NaN,-2.63,Jun 2012,10.61,90,68.5,NaN,NaN,NaN,M,"Alcohol Reference, Animated Blood, Language, P...",NaN,NaN
3,High on Life,Xbox / PC,Yes,Coming Soon,Dec 2022,NaN,-1.41,Dec 2022,0.00,NaN,NaN,First-Person Shooter,NaN,NaN,M,"Violence, Blood, Sexual Themes, Use of Drugs, ...",NaN,NaN
4,Hello Neighbor 2,Xbox / PC,Yes,Coming Soon,Dec 2022,NaN,-1.18,Dec 2022,0.00,NaN,NaN,Strategy / Puzzle,NaN,NaN,E10+,Mild Violence,NaN,NaN
5,"Warhammer 40,000: Darktide",Xbox / PC,Yes,Coming Soon,Nov 2022,NaN,-0.99,Nov 2022,0.00,NaN,NaN,Action,Exclusive,NaN,RP,NaN,NaN,NaN

In [3]:
df_gamepass.shape

(1185, 18)

In [4]:
# dataframe com a biblioteca de jogos do Xbox:

df_xbox_games = pd.read_csv('/content/drive/MyDrive/Dados Xbox/df_xbox_games.csv')
df_xbox_games.head()

,name,genre(s),developer(s),publisher(s),releasedate,addons
0,0 Day Attack on Earth,Shooter,Gulti,Square Enix,"Dec 23, 2009","['Xbox Live Arcade', 'Xbox One Backward Compat..."
1,007 Legends,First-person shooter,Eurocom,Activision,"Oct 16, 2012",[]
2,007: Quantum of Solace,First-person shooter,Treyarch,Activision,"Nov 4, 2008",[]
3,0-D Beat Drop,Puzzle & Trivia,Cyclone Zero,Arc System Works,"Nov 11, 2009",['Xbox Live Arcade']
4,1 vs. 100,Party,Xbox Game Studios,Xbox Game Studios,"Nov 19, 2009",['Xbox Live Arcade']

In [5]:
df_xbox_games.shape

(5141, 6)

In [6]:
# dataframe com dados oriundos do site True Achievements:

df_true_achievements = pd.read_csv('/content/drive/MyDrive/Dados Xbox/xbox_games_TA.csv')
df_true_achievements.head()

,Name,TA_Score,Gamerscore,Ratio,Gamers,Comp %,Comp time,Rating
0,"""ZAZEN"", zen meditation game","3,234","1,000",3.23,199,3.5,NaN,-
1,#IDARB,"1,430","1,000",1.43,"93,605",22.9,1-2 hours,2.7
2,#SinucaAttack,"1,018","1,000",1.02,"5,294",93.8,0-0.5 hours,1.9
3,>observer_,"2,055","1,000",2.06,"12,124",7.0,10-12 hours,3.4
4,0 Degrees,"1,064","1,000",1.06,"2,645",75.9,1-2 hours,2.1

In [7]:
df_true_achievements.shape

(9306, 8)

In [8]:
# dataframe com dados do Metacritic dos jogos Xbox:

df_metacritic = pd.read_csv('/content/drive/MyDrive/Dados Xbox/xbox_games_metacritic.csv')
df_metacritic.head()

,Name,Release date,Metascore,Userscore
0,Indiana Jones and the Emperor's Tomb,"June 11, 2019",tbd,tbd
1,Tom Clancy's Splinter Cell,"June 11, 2019",tbd,tbd
2,Armed and Dangerous,"June 11, 2019",tbd,tbd
3,Sphinx and the Cursed Mummy,"June 11, 2019",tbd,tbd
4,Tom Clancy's Splinter Cell: Pandora Tomorrow,"June 11, 2019",tbd,tbd

In [9]:
df_metacritic

,Name,Release date,Metascore,Userscore
0,Indiana Jones and the Emperor's Tomb,"June 11, 2019",tbd,tbd
1,Tom Clancy's Splinter Cell,"June 11, 2019",tbd,tbd
2,Armed and Dangerous,"June 11, 2019",tbd,tbd
3,Sphinx and the Cursed Mummy,"June 11, 2019",tbd,tbd
4,Tom Clancy's Splinter Cell: Pandora Tomorrow,"June 11, 2019",tbd,tbd
...,...,...,...,...
5061,Dragon Ball: The Breakers,"October 14, 2022",59,tbd
5062,Recompile,"August 19, 2021",58,4.4
5063,Dungeons & Dragons: Dark Alliance,"June 22, 2021",58,4.7
5064,Override 2: Super Mech League,"December 22, 2020",58,tbd
5065,Werewolf: The Apocalypse - Earthblood,"February 4, 2021",58,4.6

In [10]:
df_metacritic.shape

(5066, 4)

# Tratamento dos nomes dos jogos para posterior merge das bases de dados

In [11]:
# como os dados vêm de diferentes fontes, muitos dos jogos podem ter nomes escritos de maneira diferente nas diferentes
# bases de dados.

# a ideia é eliminar qualquer tipo de caráctere especial e colocar todas as letras em maiúsculo a fim de igualar os nomes
# dos jogos.

Eliminando os carácteres especiais com expressões regulares (Regex)

In [12]:
# para a tabela de jogos do Game Pass:

df_gamepass['Game'] = df_gamepass['Game'].replace(r'[' + string.punctuation +']', '', regex= True).str.upper()
df_gamepass.head()

,Game,System,xCloud,Status,Added,Removed,Months,Release,Age,Metacritic,Completion,Genre (Giantbomb),Xbox Series X|S,Owner Notes,ESRB,ESRB Content Descriptors,Public Notes,Retail
1,PERSONA 3 PORTABLE,Xbox / PC,Yes,Coming Soon,Jan 2023,NaN,-2.63,Nov 2009,13.22,89,65.5,Role-Playing,NaN,NaN,M,"Blood, Language, Partial Nudity, Sexual Themes...",NaN,NaN
2,PERSONA 4 GOLDEN,Xbox / PC,Yes,Coming Soon,Jan 2023,NaN,-2.63,Jun 2012,10.61,90,68.5,NaN,NaN,NaN,M,"Alcohol Reference, Animated Blood, Language, P...",NaN,NaN
3,HIGH ON LIFE,Xbox / PC,Yes,Coming Soon,Dec 2022,NaN,-1.41,Dec 2022,0.00,NaN,NaN,First-Person Shooter,NaN,NaN,M,"Violence, Blood, Sexual Themes, Use of Drugs, ...",NaN,NaN
4,HELLO NEIGHBOR 2,Xbox / PC,Yes,Coming Soon,Dec 2022,NaN,-1.18,Dec 2022,0.00,NaN,NaN,Strategy / Puzzle,NaN,NaN,E10+,Mild Violence,NaN,NaN
5,WARHAMMER 40000 DARKTIDE,Xbox / PC,Yes,Coming Soon,Nov 2022,NaN,-0.99,Nov 2022,0.00,NaN,NaN,Action,Exclusive,NaN,RP,NaN,NaN,NaN

In [13]:
# para a biblioteca de jogos de Xbox:

df_xbox_games['name'] = df_xbox_games['name'].replace(r'[' + string.punctuation +']', '', regex= True).str.upper()
df_xbox_games.head()

,name,genre(s),developer(s),publisher(s),releasedate,addons
0,0 DAY ATTACK ON EARTH,Shooter,Gulti,Square Enix,"Dec 23, 2009","['Xbox Live Arcade', 'Xbox One Backward Compat..."
1,007 LEGENDS,First-person shooter,Eurocom,Activision,"Oct 16, 2012",[]
2,007 QUANTUM OF SOLACE,First-person shooter,Treyarch,Activision,"Nov 4, 2008",[]
3,0D BEAT DROP,Puzzle & Trivia,Cyclone Zero,Arc System Works,"Nov 11, 2009",['Xbox Live Arcade']
4,1 VS 100,Party,Xbox Game Studios,Xbox Game Studios,"Nov 19, 2009",['Xbox Live Arcade']

In [14]:
# para os dados oriundos do True Achievements:

df_true_achievements['Name'] = df_true_achievements['Name'].replace(r'[' + string.punctuation +']', '', regex= True).str.upper()
df_true_achievements.head()

,Name,TA_Score,Gamerscore,Ratio,Gamers,Comp %,Comp time,Rating
0,ZAZEN ZEN MEDITATION GAME,"3,234","1,000",3.23,199,3.5,NaN,-
1,IDARB,"1,430","1,000",1.43,"93,605",22.9,1-2 hours,2.7
2,SINUCAATTACK,"1,018","1,000",1.02,"5,294",93.8,0-0.5 hours,1.9
3,OBSERVER,"2,055","1,000",2.06,"12,124",7.0,10-12 hours,3.4
4,0 DEGREES,"1,064","1,000",1.06,"2,645",75.9,1-2 hours,2.1

In [15]:
# para os dados dos jogos oriundos do agregador Metacritic:

df_metacritic['Name'] = df_metacritic['Name'].replace(r'[' + string.punctuation +']', '', regex= True).str.upper()
df_metacritic.head()

,Name,Release date,Metascore,Userscore
0,INDIANA JONES AND THE EMPERORS TOMB,"June 11, 2019",tbd,tbd
1,TOM CLANCYS SPLINTER CELL,"June 11, 2019",tbd,tbd
2,ARMED AND DANGEROUS,"June 11, 2019",tbd,tbd
3,SPHINX AND THE CURSED MUMMY,"June 11, 2019",tbd,tbd
4,TOM CLANCYS SPLINTER CELL PANDORA TOMORROW,"June 11, 2019",tbd,tbd

# Merge de todas as bases de dados

In [16]:
# merge dos dataframes do Game Pass e do True Achivements:

gamepass_database = pd.merge(left= df_gamepass[['Game', 'System', 'Status', 'Added', 'Removed', 'Genre (Giantbomb)','ESRB',
                            'ESRB Content Descriptors']], right= df_true_achievements, how= 'left', 
                             left_on= ['Game'], right_on= ['Name']
)

In [17]:
gamepass_database.drop(['Name'], axis= 1, inplace= True)
gamepass_database.head()

,Game,System,Status,Added,Removed,Genre (Giantbomb),ESRB,ESRB Content Descriptors,TA_Score,Gamerscore,Ratio,Gamers,Comp %,Comp time,Rating
0,PERSONA 3 PORTABLE,Xbox / PC,Coming Soon,Jan 2023,NaN,Role-Playing,M,"Blood, Language, Partial Nudity, Sexual Themes...",Unreleased,-,-,0,0.0,NaN,-
1,PERSONA 4 GOLDEN,Xbox / PC,Coming Soon,Jan 2023,NaN,NaN,M,"Alcohol Reference, Animated Blood, Language, P...",Unreleased,-,-,0,0.0,NaN,-
2,HIGH ON LIFE,Xbox / PC,Coming Soon,Dec 2022,NaN,First-Person Shooter,M,"Violence, Blood, Sexual Themes, Use of Drugs, ...",Unreleased,-,-,0,0.0,NaN,-
3,HELLO NEIGHBOR 2,Xbox / PC,Coming Soon,Dec 2022,NaN,Strategy / Puzzle,E10+,Mild Violence,Unreleased,-,-,0,0.0,NaN,-
4,WARHAMMER 40000 DARKTIDE,Xbox / PC,Coming Soon,Nov 2022,NaN,Action,RP,NaN,Unreleased,-,-,0,0.0,NaN,-

In [18]:
# merge do dataframe do Game Pass com o de jogos da biblioteca do Xbox:

gamepass_database = pd.merge(left= gamepass_database, right= df_xbox_games[['name', 'developer(s)',
                            'publisher(s)', 'addons']], how= 'left', left_on= ['Game'], right_on= ['name']
)

In [19]:
gamepass_database.drop(['name'], axis= 1, inplace= True)
gamepass_database.head()

,Game,System,Status,Added,Removed,Genre (Giantbomb),ESRB,ESRB Content Descriptors,TA_Score,Gamerscore,Ratio,Gamers,Comp %,Comp time,Rating,developer(s),publisher(s),addons
0,PERSONA 3 PORTABLE,Xbox / PC,Coming Soon,Jan 2023,NaN,Role-Playing,M,"Blood, Language, Partial Nudity, Sexual Themes...",Unreleased,-,-,0,0.0,NaN,-,Atlus,Sega,['']
1,PERSONA 4 GOLDEN,Xbox / PC,Coming Soon,Jan 2023,NaN,NaN,M,"Alcohol Reference, Animated Blood, Language, P...",Unreleased,-,-,0,0.0,NaN,-,Atlus,Sega,['']
2,HIGH ON LIFE,Xbox / PC,Coming Soon,Dec 2022,NaN,First-Person Shooter,M,"Violence, Blood, Sexual Themes, Use of Drugs, ...",Unreleased,-,-,0,0.0,NaN,-,NaN,NaN,NaN
3,HELLO NEIGHBOR 2,Xbox / PC,Coming Soon,Dec 2022,NaN,Strategy / Puzzle,E10+,Mild Violence,Unreleased,-,-,0,0.0,NaN,-,Dynamic Pixels,TinyBuild,['']
4,WARHAMMER 40000 DARKTIDE,Xbox / PC,Coming Soon,Nov 2022,NaN,Action,RP,NaN,Unreleased,-,-,0,0.0,NaN,-,Fatshark,Fatshark,['Optimized for Xbox Series X/S']

In [20]:
# por fim, merge entre o dataframe do Game Pass e do Metacritic:

gamepass_database = pd.merge(left= gamepass_database, right= df_metacritic, how= 'left', left_on= ['Game'],
                             right_on= ['Name']
)

In [21]:
gamepass_database.drop(['Name'], axis= 1, inplace= True)
gamepass_database.head()

,Game,System,Status,Added,Removed,Genre (Giantbomb),ESRB,ESRB Content Descriptors,TA_Score,Gamerscore,...,Gamers,Comp %,Comp time,Rating,developer(s),publisher(s),addons,Release date,Metascore,Userscore
0,PERSONA 3 PORTABLE,Xbox / PC,Coming Soon,Jan 2023,NaN,Role-Playing,M,"Blood, Language, Partial Nudity, Sexual Themes...",Unreleased,-,...,0,0.0,NaN,-,Atlus,Sega,[''],NaN,NaN,NaN
1,PERSONA 4 GOLDEN,Xbox / PC,Coming Soon,Jan 2023,NaN,NaN,M,"Alcohol Reference, Animated Blood, Language, P...",Unreleased,-,...,0,0.0,NaN,-,Atlus,Sega,[''],NaN,NaN,NaN
2,HIGH ON LIFE,Xbox / PC,Coming Soon,Dec 2022,NaN,First-Person Shooter,M,"Violence, Blood, Sexual Themes, Use of Drugs, ...",Unreleased,-,...,0,0.0,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN
3,HELLO NEIGHBOR 2,Xbox / PC,Coming Soon,Dec 2022,NaN,Strategy / Puzzle,E10+,Mild Violence,Unreleased,-,...,0,0.0,NaN,-,Dynamic Pixels,TinyBuild,[''],NaN,NaN,NaN
4,WARHAMMER 40000 DARKTIDE,Xbox / PC,Coming Soon,Nov 2022,NaN,Action,RP,NaN,Unreleased,-,...,0,0.0,NaN,-,Fatshark,Fatshark,['Optimized for Xbox Series X/S'],NaN,NaN,NaN

In [22]:
gamepass_database.shape

(1197, 21)

# Alguns tratamentos para exportar a base de dados do Game Pass

In [23]:
gamepass_database.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1197 entries, 0 to 1196
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Game                      1197 non-null   object
 1   System                    1196 non-null   object
 2   Status                    1196 non-null   object
 3   Added                     1197 non-null   object
 4   Removed                   646 non-null    object
 5   Genre (Giantbomb)         1192 non-null   object
 6   ESRB                      678 non-null    object
 7   ESRB Content Descriptors  594 non-null    object
 8   TA_Score                  926 non-null    object
 9   Gamerscore                926 non-null    object
 10  Ratio                     926 non-null    object
 11  Gamers                    926 non-null    object
 12  Comp %                    926 non-null    float64
 13  Comp time                 846 non-null    object
 14  Rating                    926 non-null    object
 15  developer(s)              733 non-null    object
 16  publisher(s)              733 non-null    object
 17  addons                    733 non-null    object
 18  Release date              753 non-null    object
 19  Metascore                 753 non-null    object
 20  Userscore                 753 non-null    object
dtypes: float64(1), object(20)
memory usage: 205.7+ KB

In [24]:
# a fim de padronizar os nomes das colunas, faz-se a sua renomeação:

gamepass_database.columns = ['game', 'system', 'status', 'added', 'removed', 'genre', 'esrb', 'esrb content', 'ta_score', 'gamerscore', 'ratio',
                            'gamers', 'comp_%', 'comp_time', 'rating', 'developer', 'publisher', 'addons', 'release_date', 'metascore', 'userscore']

In [25]:
gamepass_database.head()

,game,system,status,added,removed,genre,esrb,esrb content,ta_score,gamerscore,...,gamers,comp_%,comp_time,rating,developer,publisher,addons,release_date,metascore,userscore
0,PERSONA 3 PORTABLE,Xbox / PC,Coming Soon,Jan 2023,NaN,Role-Playing,M,"Blood, Language, Partial Nudity, Sexual Themes...",Unreleased,-,...,0,0.0,NaN,-,Atlus,Sega,[''],NaN,NaN,NaN
1,PERSONA 4 GOLDEN,Xbox / PC,Coming Soon,Jan 2023,NaN,NaN,M,"Alcohol Reference, Animated Blood, Language, P...",Unreleased,-,...,0,0.0,NaN,-,Atlus,Sega,[''],NaN,NaN,NaN
2,HIGH ON LIFE,Xbox / PC,Coming Soon,Dec 2022,NaN,First-Person Shooter,M,"Violence, Blood, Sexual Themes, Use of Drugs, ...",Unreleased,-,...,0,0.0,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN
3,HELLO NEIGHBOR 2,Xbox / PC,Coming Soon,Dec 2022,NaN,Strategy / Puzzle,E10+,Mild Violence,Unreleased,-,...,0,0.0,NaN,-,Dynamic Pixels,TinyBuild,[''],NaN,NaN,NaN
4,WARHAMMER 40000 DARKTIDE,Xbox / PC,Coming Soon,Nov 2022,NaN,Action,RP,NaN,Unreleased,-,...,0,0.0,NaN,-,Fatshark,Fatshark,['Optimized for Xbox Series X/S'],NaN,NaN,NaN

In [26]:
# por questões de organização e estética, reorganiza-se algumas colunas:

gamepass_database = gamepass_database[['game', 'system', 'status', 'release_date', 'added', 'removed', 'genre', 'developer', 'publisher', 'esrb', 'esrb content', 
                                      'addons', 'ta_score', 'gamerscore', 'ratio', 'gamers', 'comp_%', 'comp_time', 'rating', 'metascore', 'userscore']]

# Exportando o dataframe

In [27]:
gamepass_database.to_csv('database_gamepass.csv', index= False)